name: Cross compline release
on: [workflow_call]

jobs:
  build-release:
    name: Cross compline release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2

      # - run: curl -L -O https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
      # - run: tar -xzf cargo-binstall-x86_64-unknown-linux-musl.tgz
      # - run: mv cargo-binstall $HOME/.cargo/bin
      - run: cargo install cross --git https://github.com/cross-rs/cross
      # - run: cargo binstall --no-confirm --no-symlinks cross
      - run: npm i
      - run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: linux-windows-targets
          path: |
            target/**/*.so
            target/**/*.dll
            target/**/*.dylib
          retention-days: 5
