name: Ubuntu release builds
on: [workflow_call]

jobs:
  build-release:
    name: Ubuntu release builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu
          targets: aarch64-unknown-linux-musl
          targets: armv7-unknown-linux-gnueabi
          targets: armv7-unknown-linux-musleabi
          targets: i686-unknown-linux-gnu
          targets: i686-unknown-linux-musl
          targets: x86_64-unknown-linux-gnu
          targets: x86_64-unknown-linux-musl
          targets: powerpc64-unknown-linux-gnu
          targets: powerpc64le-unknown-linux-gnu
          targets: s390x-unknown-linux-gnu
          targets: riscv64gc-unknown-linux-gnu

      # - uses: actions/setup-node@v3
      # - uses: docker-practice/actions-setup-docker@master
      #   timeout-minutes: 12
      # - run: cargo install cross --git https://github.com/cross-rs/cross
      # - run: npm i
      # - run: npm run build

      - run: cargo build --release --target aarch64-unknown-linux-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: linux-arm64.node
          path: target/aarch64-unknown-linux-gnu/release/libnode_systemstat.so
      - run: cargo build --release --target aarch64-unknown-linux-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: linux-arm64-musl.node
          path: target/aarch64-unknown-linux-musl/release/libnode_systemstat.so

      - run: cargo build --release --target armv7-unknown-linux-gnueabi
      - uses: actions/upload-artifact@v3
        with:
          name: linux-armv7l.node
          path: target/armv7-unknown-linux-gnueabi/release/libnode_systemstat.so
      - run: cargo build --release --target armv7-unknown-linux-musleabi
      - uses: actions/upload-artifact@v3
        with:
          name: linux-armv7l-musl.node
          path: target/armv7-unknown-linux-musleabi/release/libnode_systemstat.so

      - run: cargo build --release --target i686-unknown-linux-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: linux-x86.node
          path: target/i686-unknown-linux-gnu/release/libnode_systemstat.so
      - run: cargo build --release --target i686-unknown-linux-musl
      - uses: actions/upload-artifact@v3
        with:
          name: linux-x86-musl.node
          path: target/i686-unknown-linux-musl/release/libnode_systemstat.so

      - run: cargo build --release --target x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: linux-x64.node
          path: target/x86_64-unknown-linux-gnu/release/libnode_systemstat.so
      - run: cargo build --release --target x86_64-unknown-linux-musl
      - uses: actions/upload-artifact@v3
        with:
          name: linux-x64-musl.node
          path: target/x86_64-unknown-linux-musl/release/libnode_systemstat.so

      - run: cargo build --release --target powerpc64-unknown-linux-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: linux-ppc64.node
          path: target/powerpc64-unknown-linux-gnu/release/libnode_systemstat.so
      - run: cargo build --release --target powerpc64le-unknown-linux-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: linux-ppc64le.node
          path: target/powerpc64le-unknown-linux-gnu/release/libnode_systemstat.so

      - run: cargo build --release --target s390x-unknown-linux-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: linux-s390x.node
          path: target/s390x-unknown-linux-gnu/release/libnode_systemstat.so

      - run: cargo build --release --target riscv64gc-unknown-linux-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: linux-riskv64.node
          path: target/riscv64gc-unknown-linux-gnu/release/libnode_systemstat.so