name: test suite
on: [workflow_dispatch, push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features
