name: Build release targets
on: [workflow_dispatch]

jobs:
  build-release:
    name: build all releases
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
      # - uses: actions/setup-node@v3
      # - uses: docker-practice/actions-setup-docker@master
      #   timeout-minutes: 12
      # - run: cargo install cross --git https://github.com/cross-rs/cross
      # - run: npm i
      # - run: npm run build
      - run: cargo build --release --target aarch64-apple-darwin
      - uses: actions/upload-artifact@v3
        with:
          name: darwin-arm64.node
          path: target/aarch64-apple-darwin/release/libnode_systemstat.dylib
      - run: cargo build --release --target x86_64-apple-darwin
      - uses: actions/upload-artifact@v3
        with:
          name: darwin-x64.node
          path: target/x86_64-apple-darwin/release/libnode_systemstat.dylib
