name: test suite
on: [workflow_dispatch]

jobs:
  test:
    name: cargo test
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-node@v3
      - run: npm run build 
