name: Compile releases
# on: [workflow_dispatch, push, pull_request]
on: [workflow_dispatch]

jobs:
  compile-mac:
    uses: ./.github/workflows/mac_compile.yaml
  compile-linux-windows:
    uses: ./.github/workflows/cross_compile.yaml

  continue:
    name: job name
    needs: [compile-mac, compile-linux-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: |
          mkdir target
          mv linux-windows-targets/ target
          mv mac-targets/ target
          ls -R

      - name: Copy build artifacts from targets to node native dirs
        run: npm run copy

      - name: Publish --dry
        run: |
          git config --global user.name 'Automated publish'
          git config --global user.email 'mocsy@users.noreply.github.com'
          npm i
          npm publish --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}